# Generated by Django 5.1.4 on 2025-01-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_blog', '0004_alter_tags_options_tags_slug_alter_post_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(),
        ),
    ]
