# Generated by Django 5.1.4 on 2025-01-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_blog', '0006_alter_tags_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='slug',
        ),
    ]
