# Generated by Django 5.1.4 on 2025-01-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_blog', '0007_remove_tags_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
