# Generated by Django 5.1.4 on 2025-01-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_blog', '0009_alter_tags_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RemoveField(
            model_name='tags',
            name='slug',
        ),
    ]
