# Generated by Django 5.1.4 on 2025-02-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_blog', '0010_alter_tags_options_remove_tags_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
